apiVersion: v1
kind: Pod
metadata:
  name: clickhouse-db
  labels:
    app: ch-db
spec:
  containers:
  - name: clickhouse-db
    image: f0m41h4u7/custom-clickhouse-serv 
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-svc
spec:
  type: NodePort
  selector:
    app: ch-db
  ports:
    - protocol: TCP
      port: 9000
      nodePort: 30000
