apiVersion: v1
kind: Pod
metadata:
  name: clickhouse-db
  namespace: owl
  labels:
    app: ch-db
spec:
  containers:
  - name: clickhouse-db
    image: yandex/clickhouse-server  
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-svc
  namespace: owl
spec:
  type: NodePort
  selector:
    app: ch-db
  ports:
    - name: client-port
      protocol: TCP
      port: 9000
      nodePort: 30001
    - name: http-port
      protocol: TCP
      port: 8123
      nodePort: 30002
