apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbit
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:3.8.3-alpine  
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  selector:
    app: rabbit
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
