apiVersion: v1
kind: Pod
metadata:
  name: json 
  labels:
    app: json
spec:
  containers:
  - name: json 
    image: f0m41h4u7/owl-web
---
apiVersion: v1
kind: Service
metadata:
  name: json-svc
spec:
  type: NodePort
  selector:
    app: json
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30001
