apiVersion: v1
kind: Pod
metadata:
  name: front
  namespace: owl
  labels:
    app: front
spec:
  containers:
  - name: front 
    image: inviewteam/owl-front
    securityContext:
       capabilities:
         add:
           - NET_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-svc
  namespace: owl
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - name: front-port
      protocol: TCP
      port: 80
      nodePort: 31337
