apiVersion: v1
kind: Pod
metadata:
  name: front
  namespace: owl
  labels:
    app: front
spec:
  containers:
  - name: restapi
    image: inviewteam/owl-front
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: owl
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31337
